### ISSUE TITLE
Incorrect names for Gen1

### ISSUE THREAD

**Issue by RainingChain** [fattard/MissingEventFlagsCheckerPlugin#1]
Reflect is TM33, not TM30. In Gen1, the item name is Elixer instead of Elixir. TM36 is Selfdestruct instead of Self-Destruct.

**Comment by fattard** [comment]
Fixed the internal database number for TM33 Reflect and spelling names for Elixer.
#https://github.com/fattard/MissingEventFlagsCheckerPlugin/commit/01829c10229f511eeb84d8935b24d2a8ab3f93cd

For the move names in the TMs, I will keep the modern names, as the spelling was that way due to number of characters restriction.

If you need the correct Gen1 names for some parsing, I'm planning a localization override for the internal DB, so you will be able to use your own texts instead of the provided ones.
